// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection: Prisma Migrate uses
    // session-level advisory locks that pgbouncer-style transaction pooling
    // breaks. Vercel's Neon integration provides DATABASE_URL_UNPOOLED for
    // this; fall back to DATABASE_URL for setups without a separate direct
    // connection string (e.g. local Postgres).
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
